import os
import time


print("")
print("colorize")
print("")
os.system("gem install colorize")
time.sleep(1)
print("")
print("selenium-webdriver")
print("")
os.system("gem install selenium-webdriver")
time.sleep(1)
print("")
print("terminal-table")
print("")
os.system("gem install terminal-table")
time.sleep(1)
print("")
print("progress_bar")
print("")
os.system("gem install progress_bar")
time.sleep(1)
print("")
print("XSpear")
print("")
os.system("gem install XSpear")
time.sleep(1)
print("")
print("python3-dnspython")
print("")
os.system("sudo apt-get install python3-dnspython")
time.sleep(1)
print("")
print("urlcrazy")
print("")
os.system("apt-get install urlcrazy")
time.sleep(1)
print("")
print("setuptools")
print("")
os.system("pip install --upgrade setuptools")
time.sleep(1)
print("")
print("httpie")
print("")
os.system("apt-get install httpie")
time.sleep(1)
print("")
print("sublist3r")
print("")
os.system("apt-get install sublist3r")
time.sleep(1)
print("")
print("dnsmap")
print("")
os.system("apt-get install dnsmap")
time.sleep(1)
print("")
print("dnsrecon")
print("")
os.system("apt-get install dnsrecon")
time.sleep(1)
print("")
print("whois")
print("")
os.system("apt-get install whois")
time.sleep(1)
print("")
print("traceroute")
print("")
os.system("sudo apt-get install whatweb -y")
time.sleep(1)
print("                                         \033[1;33m[\033[1;31m!\033[1;33m]\033[0m \033[1;34mTool Run again Requirements Success >_o\033[0m \033[1;33m[\033[1;31m!\033[1;33m]\033[0m")